/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yfaceswap_FaceSwapLib */

#ifndef _Included_com_yfaceswap_FaceSwapLib
#define _Included_com_yfaceswap_FaceSwapLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yfaceswap_FaceSwapLib
 * Method:    Init
 * Signature: ()Z
 */
	JNIEXPORT jboolean JNICALL Java_com_yfaceswap_FaceSwapLib_Init
	(JNIEnv *, jobject,jstring,jstring);

/*
 * Class:     com_yfaceswap_FaceSwapLib
 * Method:    Finalize
 * Signature: ()Z
 */
	JNIEXPORT jboolean JNICALL Java_com_yfaceswap_FaceSwapLib_Finalize
	(JNIEnv *, jobject);

/*
 * Class:     com_yfaceswap_FaceSwapLib
 * Method:    Calculate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
	JNIEXPORT jstring JNICALL Java_com_yfaceswap_FaceSwapLib_Calculate
	(JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
